// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using R54_M11_Class_01_Work_02.Models;

#nullable disable

namespace R54_M11_Class_01_Work_02.Migrations
{
    [DbContext(typeof(ProductDbContext))]
    partial class ProductDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("R54_M11_Class_01_Work_02.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<bool?>("OnSale")
                        .HasColumnType("bit");

                    b.Property<string>("Picture")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Price")
                        .HasColumnType("money");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Picture = "1jpg",
                            Price = 1424m,
                            ProductName = "Product 1",
                            Size = 2
                        },
                        new
                        {
                            ProductId = 2,
                            Picture = "2jpg",
                            Price = 1373m,
                            ProductName = "Product 2",
                            Size = 3
                        },
                        new
                        {
                            ProductId = 3,
                            Picture = "3jpg",
                            Price = 1481m,
                            ProductName = "Product 3",
                            Size = 1
                        },
                        new
                        {
                            ProductId = 4,
                            Picture = "4jpg",
                            Price = 1883m,
                            ProductName = "Product 4",
                            Size = 2
                        },
                        new
                        {
                            ProductId = 5,
                            Picture = "5jpg",
                            Price = 1228m,
                            ProductName = "Product 5",
                            Size = 3
                        });
                });

            modelBuilder.Entity("R54_M11_Class_01_Work_02.Models.Sale", b =>
                {
                    b.Property<int>("SaleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SaleId"));

                    b.Property<DateTime?>("Date")
                        .IsRequired()
                        .HasColumnType("date");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int?>("Quantity")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("SaleId");

                    b.HasIndex("ProductId");

                    b.ToTable("Sales");

                    b.HasData(
                        new
                        {
                            SaleId = 1,
                            Date = new DateTime(2022, 6, 4, 15, 34, 46, 832, DateTimeKind.Local).AddTicks(8980),
                            ProductId = 1,
                            Quantity = 148
                        },
                        new
                        {
                            SaleId = 2,
                            Date = new DateTime(2022, 8, 24, 15, 34, 46, 832, DateTimeKind.Local).AddTicks(9007),
                            ProductId = 2,
                            Quantity = 111
                        },
                        new
                        {
                            SaleId = 3,
                            Date = new DateTime(2022, 8, 8, 15, 34, 46, 832, DateTimeKind.Local).AddTicks(9016),
                            ProductId = 3,
                            Quantity = 104
                        },
                        new
                        {
                            SaleId = 4,
                            Date = new DateTime(2022, 8, 11, 15, 34, 46, 832, DateTimeKind.Local).AddTicks(9024),
                            ProductId = 4,
                            Quantity = 153
                        },
                        new
                        {
                            SaleId = 5,
                            Date = new DateTime(2022, 6, 3, 15, 34, 46, 832, DateTimeKind.Local).AddTicks(9032),
                            ProductId = 5,
                            Quantity = 128
                        },
                        new
                        {
                            SaleId = 6,
                            Date = new DateTime(2022, 7, 1, 15, 34, 46, 832, DateTimeKind.Local).AddTicks(9042),
                            ProductId = 1,
                            Quantity = 156
                        },
                        new
                        {
                            SaleId = 7,
                            Date = new DateTime(2022, 5, 21, 15, 34, 46, 832, DateTimeKind.Local).AddTicks(9051),
                            ProductId = 2,
                            Quantity = 138
                        },
                        new
                        {
                            SaleId = 8,
                            Date = new DateTime(2022, 8, 20, 15, 34, 46, 832, DateTimeKind.Local).AddTicks(9058),
                            ProductId = 3,
                            Quantity = 144
                        });
                });

            modelBuilder.Entity("R54_M11_Class_01_Work_02.Models.Sale", b =>
                {
                    b.HasOne("R54_M11_Class_01_Work_02.Models.Product", "Product")
                        .WithMany("Sales")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("R54_M11_Class_01_Work_02.Models.Product", b =>
                {
                    b.Navigation("Sales");
                });
#pragma warning restore 612, 618
        }
    }
}
